"""Package approved design data as Lua; this is an authoring step, not a test."""
import json
import pathlib
import re
from expanded_affix_data import families as expanded_families, EXCLUDED, tier_text
from weapon_affix_rules import policy as weapon_policy

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / 'mod/scripts/randomisedbasicloot'


def lua(value):
    if value is None:
        return 'nil'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return '{' + ','.join(lua(v) for v in value) + '}'
    return '{' + ','.join('[' + lua(k) + ']=' + lua(v) for k, v in value.items()) + '}'


SLOTS = {
    'Head': ['helmet'], 'Cuirass': ['cuirass'], 'Hands': ['left_glove', 'right_glove', 'left_gauntlet', 'right_gauntlet', 'left_bracer', 'right_bracer'],
    'feet': ['boots', 'shoes'], 'Feet': ['boots', 'shoes'], 'greaves': ['greaves'],
    'pants': ['pants'], 'skirts': ['skirt'], 'robes': ['robe'], 'Robes': ['robe'],
    'shirts': ['shirt'], 'belts': ['belt'], 'rings': ['ring'], 'amulets': ['amulet'],
    'jewelry': ['ring', 'amulet'], 'Jewelry': ['ring', 'amulet'],
    'body clothing': ['shirt', 'pants', 'skirt', 'robe'], 'Body clothing': ['shirt', 'pants', 'skirt', 'robe'],
}
for label, values in list(SLOTS.items()):
    SLOTS[label.lower()] = values
SLOTS['boots'] = ['boots']
SLOTS['shields'] = ['shield']
ATTRS = {'strength', 'intelligence', 'willpower', 'agility', 'speed', 'endurance', 'personality', 'luck'}
WEAPON_SKILLS = {'Short Blade': ['short_blade'], 'Long Blade': ['long_blade_one_hand', 'long_blade_two_hand'],
                 'Axe': ['axe_one_hand', 'axe_two_hand'], 'Blunt Weapon': ['blunt_one_hand', 'blunt_two_hand_close', 'blunt_two_hand_wide'],
                 'Spear': ['spear'], 'Marksman': ['bow', 'crossbow']}


def main():
    (OUT / 'weapon_affix_policy.lua').write_text('-- Generated from tools/weapon_affix_rules.py.\nreturn ' + lua(weapon_policy()) + '\n', encoding='utf-8')
    data = json.loads((ROOT / 'data/loot-design.json').read_text(encoding='utf-8'))
    sources = {'Morrowind (Base Game)': 'base', 'Tribunal': 'tribunal', 'Bloodmoon': 'bloodmoon', 'OAAB Data': 'oaab'}
    for source, pack in sources.items():
        groups = {}
        for entry in data['uniqueTemplates']:
            if entry['source'] != source:
                continue
            keys = ('id', 'baseId', 'name', 'record', 'effects', 'templateVersion', 'category', 'slot', 'mode', 'charge', 'cost', 'isAutocalc', 'weight')
            groups.setdefault(entry['baseId'], []).append({k: entry[k] for k in keys if k in entry})
        (OUT / (pack + '_uniques.lua')).write_text('-- Generated by tools/export_runtime_design.py; fixed reviewed registry drafts.\nreturn ' + lua(groups) + '\n', encoding='utf-8')

    families = []
    side = 'prefix'
    for line in (ROOT / 'docs/reports/modifier-catalogue.md').read_text(encoding='utf-8').splitlines():
        if line.startswith('## Prefixes') or line.startswith('### Weapon Prefixes'):
            side = 'prefix'
        elif line.startswith('## Suffixes') or line.startswith('### Weapon Suffixes') or line.startswith('### Special Modifier'):
            side = 'suffix'
        if not line.startswith('|'):
            continue
        cells = [c.strip() for c in line.strip('|').split('|')]
        if len(cells) < 9 or not any('**' in c for c in cells[2:8]):
            continue
        effect = cells[1]
        spec = {'side': side, 'tiers': {}}
        if effect.startswith('Fortify '):
            target = effect[8:]
            ident = target.lower().replace(' ', '')
            if ident in ATTRS:
                spec.update(effect='fortifyattribute', attribute=ident)
            elif ident in ('health', 'magicka', 'fatigue'):
                spec['effect'] = 'fortify' + ident
            else:
                spec.update(effect='fortifyskill', skill=ident)
        else:
            spec['effect'] = effect.lower().replace(' ', '')
        if spec['effect'] == 'detectcreature':
            spec['effect'] = 'detectanimal'
        spec['id'] = spec['effect'] + ':' + spec.get('attribute', spec.get('skill', ''))
        for tier, cell in enumerate(cells[2:8], 1):
            match = re.search(r'\*\*([^*]+)\*\*\s*\((\d+)', cell)
            if match:
                spec['tiers'][str(tier)] = {'name': match[1], 'magnitude': int(match[2])}
        scope = cells[8]
        if '`' in scope:
            spec['baseIds'] = re.findall(r'`([^`]+)`', scope)
        elif effect.startswith('Fortify ') and effect[8:] in WEAPON_SKILLS:
            spec.update(category='weapon', slots=WEAPON_SKILLS[effect[8:]])
        elif 'Melee weapons' in scope or scope == 'Short blades, spears':
            spec.update(category='weapon', melee=True)
            if scope == 'Short blades, spears':
                spec['slots'] = ['short_blade', 'spear']
            spec['mode'] = 'CastOnStrike'
        elif scope == 'Wearables':
            spec['wearable'] = True
        elif scope == 'Clothing':
            spec['category'] = 'clothing'
        else:
            spec['slots'] = sorted({s for token, slots in SLOTS.items() if token.lower() in scope.lower() for s in slots})
            spec['wearable'] = True
            if 'Armor' in scope:
                spec['allArmor'] = True
        families.append(spec)
    (OUT / 'magic_catalogue.lua').write_text('-- Generated tier names and magnitudes from docs/reports/modifier-catalogue.md.\nreturn ' + lua(families) + '\n', encoding='utf-8')
    expanded = expanded_families()
    (OUT / 'expanded_catalogue.lua').write_text('-- Generated by tools/export_runtime_design.py from expanded_affix_data.py.\nreturn ' + lua(expanded) + '\n', encoding='utf-8')
    (ROOT / 'docs/reports/expanded-affixes.json').write_text(json.dumps(expanded, indent=2) + '\n', encoding='utf-8')
    rows = ['# Expanded Spell-Effect Affixes', '',
            'Ordinary affixes only; unique templates and existing generated records are unchanged.', '',
            'Enabled by `expandedAffixes` / **Expanded Spell-Effect Affixes** in Options > Scripts.',
            'Every eligible base can use every available tier. Functionally identical extra tiers are omitted.',
            'Water Breathing/Walking: T1-T3 on use (15/30/60 seconds), T4 clean CE; no T5/T6.',
            'Levitate: T1-T3 on use (15 points for 15/30/60 seconds), T4-T6 CE (15/25/50 points).',
            'Slowfall: T1-T3 on use (15/30/60 seconds), T4-T6 CE with increasing magnitude; see utility catalogue.',
            'Light, Night Eye, detection, Telekinesis, Swift Swim and Jump remain CE at every tier.',
            'Binary timed effects scale duration; instant-effect tiers scale charge capacity, not magnitude.',
            'Charged effects store native-formula cost explicitly, with at least (3 + highest magic tier) casts before Enchant skill adjustments.',
            'Health, fatigue and magicka regeneration have only T1-T3 (1/2/3 points/second), amulet-only suffixes, weight x0.1. Only one regeneration affix can appear per item.',
            'Command has only T1-T3 (level caps 5/15/25); Calm/Frenzy/Rally/Demoralize/Turn Undead have only T1-T3 (AI magnitudes 25/50/100). All last 10/20/30 seconds.',
            'Open reaches lock level 85; Disintegrate Armor/Weapon reach 60 points/second for one second; Jump reaches 35 points CE.',
            'Reflect: CE amulet suffix, 3/5/7/9/12/15 percent. Spell Absorption: CE ring/amulet suffix, only T1-T5 at 1/2/3/4/5 percent. Both have family weight x0.25.',
            'Paralysis: melee strike suffix, 2/3/5/7/10/15 seconds, family weight x0.25; calibrated against vanilla 10-second Jinkblades and 20-second Steel Jinkblade of the Aegis.',
            'Grouped attribute/skill variants share a total family weight, avoiding dilution by dozens of parameter variants.',
            'These are development allocations awaiting permitted engine testing, especially regeneration stacking and repeated cast-on-use effects.', '',
            'Tribunal/Bloodmoon effects require the master loaded AND its source switch enabled.',
            'Summons and bound equipment also require the records referenced by the engine GMSTs.',
            'Different native enchantment modes cannot combine on one item. Physical modifiers can combine with any mode.', '',
            'Weapon values below are baseline allocations. Ordinary control durations are class-scaled; staves instead cast on use, on target with stronger magnitudes and a fixed 3-foot area. See [Weapon Affix Delivery](../WEAPON-AFFIX-DELIVERY.md); the website shows resolved class values.', '',
            '| Effect | Mode / Target | Slots | Weight | Requirement | T1 | T2 | T3 | T4 | T5 | T6 |',
            '| --- | --- | --- | ---: | --- | --- | --- | --- | --- | --- | --- |']
    for f in expanded:
        values = [tier_text(f, tier) for tier in range(1, 7)]
        requirement = ', '.join(filter(None, [f.get('expansion'), f.get('requiredCreatureGMST'),
                                             ', '.join(f.get('requiredItemGMSTs', []))])) or 'Effect record / valid target'
        modes = ', '.join(dict.fromkeys(t.get('mode', f['mode']) for t in f['tiers'].values()))
        rows.append('| ' + ' | '.join([f['label'], modes + ' / ' + f['range'],
                                      ', '.join(f['slots']), f"{f['weight']:.4g}", requirement, *values]) + ' |')
    rows.extend(['', '## Explicit Exclusions', '', '| Effect ID | Reason |', '| --- | --- |'])
    rows.extend('| ' + effect + ' | ' + reason + ' |' for effect, reason in EXCLUDED.items())
    rows.extend(['', '## Sources', '',
                 '[OpenMW effect IDs and expansion assignments](https://github.com/OpenMW/openmw/blob/master/components/esm3/loadmgef.cpp).',
                 '[Native summon mappings](https://github.com/OpenMW/openmw/blob/master/apps/openmw/mwmechanics/summoning.cpp).',
                 '[Native bound equipment mappings](https://github.com/OpenMW/openmw/blob/master/apps/openmw/mwmechanics/spelleffects.cpp).',
                 '[Native cost calculation](https://github.com/OpenMW/openmw/blob/master/apps/openmw/mwmechanics/spellutil.cpp).',
                 'UESP Spell Effects was unavailable to automated browsing; engine sources were used instead.',
                 'No tests were run for this update.'])
    (ROOT / 'docs/reports/expanded-affixes.md').write_text('\n'.join(rows) + '\n', encoding='utf-8')
    print('Exported unique source packs and magic catalogue for the full development build.')


if __name__ == '__main__':
    main()
