-- Static base-game pool. Generated from source Morrowind.esm for review.
-- Loaded by the development runtime. Missing IDs are skipped.
-- See docs/reports/included-items-report.md for included items and scope.
return {
    armor = {
        helmet = {
            "bonemold_helm",
            "chitin helm",
            "dreugh_helm",
            "dwemer_helm",
            "fur_helm",
            "glass_helm",
            "imperial helmet armor",
            "imperial_chain_coif_helm",
            "iron_helmet",
            "netch_leather_boiled_helm",
            "netch_leather_helm",
            "nordic_iron_helm",
            "orcish_helm",
            "silver_helm",
            "steel_helm",
            "trollbone_helm",
        },
        cuirass = {
            "bonemold_cuirass",
            "chitin cuirass",
            "dreugh_cuirass",
            "dwemer_cuirass",
            "fur_bearskin_cuirass",
            "fur_cuirass",
            "glass_cuirass",
            "imperial cuirass_armor",
            "imperial_chain_cuirass",
            "imperial_studded_cuirass",
            "iron_cuirass",
            "netch_leather_boiled_cuirass",
            "netch_leather_cuirass",
            "nordic_iron_cuirass",
            "nordic_ringmail_cuirass",
            "orcish_cuirass",
            "silver_cuirass",
            "steel_cuirass",
            "trollbone_cuirass",
        },
        left_pauldron = {
            "bonemold_pauldron_l",
            "chitin pauldron - left",
            "dwemer_pauldron_left",
            "fur_pauldron_left",
            "glass_pauldron_left",
            "imperial left pauldron",
            "imperial_chain_pauldron_left",
            "iron_pauldron_left",
            "netch_leather_pauldron_left",
            "orcish_pauldron_left",
            "steel_pauldron_left",
        },
        right_pauldron = {
            "bonemold_pauldron_r",
            "chitin pauldron - right",
            "dwemer_pauldron_right",
            "fur_pauldron_right",
            "glass_pauldron_right",
            "imperial right pauldron",
            "imperial_chain_pauldron_right",
            "iron_pauldron_right",
            "netch_leather_pauldron_right",
            "orcish_pauldron_right",
            "steel_pauldron_right",
        },
        greaves = {
            "bonemold_greaves",
            "chitin greaves",
            "dwemer_greaves",
            "fur_greaves",
            "glass_greaves",
            "imperial_chain_greaves",
            "imperial_greaves",
            "iron_greaves",
            "netch_leather_greaves",
            "orcish_greaves",
            "steel_greaves",
        },
        boots = {
            "bonemold_boots",
            "chitin boots",
            "dwemer_boots",
            "fur_boots",
            "glass_boots",
            "imperial boots",
            "iron boots",
            "netch_leather_boots",
            "orcish_boots",
            "steel_boots",
        },
        left_gauntlet = {
            "chitin guantlet - left",
            "fur_gauntlet_left",
            "imperial left gauntlet",
            "iron_gauntlet_left",
            "netch_leather_gauntlet_left",
            "steel_gauntlet_left",
        },
        right_gauntlet = {
            "chitin guantlet - right",
            "fur_gauntlet_right",
            "imperial right gauntlet",
            "iron_gauntlet_right",
            "netch_leather_gauntlet_right",
            "steel_gauntlet_right",
        },
        shield = {
            "bonemold_shield",
            "bonemold_towershield",
            "chitin_shield",
            "chitin_towershield",
            "dreugh_shield",
            "dwemer_shield",
            "glass_shield",
            "glass_towershield",
            "imperial shield",
            "iron_shield",
            "iron_towershield",
            "netch_leather_shield",
            "netch_leather_towershield",
            "nordic_leather_shield",
            "orcish_towershield",
            "steel_shield",
            "steel_towershield",
            "trollbone_shield",
        },
        left_bracer = {
            "bonemold_bracer_left",
            "cloth bracer left",
            "dwemer_bracer_left",
            "fur_bracer_left",
            "glass_bracer_left",
            "iron_bracer_left",
            "left leather bracer",
        },
        right_bracer = {
            "bonemold_bracer_right",
            "cloth bracer right",
            "dwemer_bracer_right",
            "fur_bracer_right",
            "glass_bracer_right",
            "iron_bracer_right",
            "right leather bracer",
        },
    },
    weapon = {
        short_blade = {
            "chitin dagger",
            "chitin shortsword",
            "dwarven shortsword",
            "imperial shortsword",
            "iron dagger",
            "iron shortsword",
            "iron tanto",
            "iron wakizashi",
            "silver dagger",
            "silver shortsword",
            "steel dagger",
            "steel shortsword",
            "steel tanto",
            "steel wakizashi",
        },
        long_blade_one_hand = {
            "imperial broadsword",
            "iron broadsword",
            "iron longsword",
            "iron saber",
            "nordic broadsword",
            "silver longsword",
            "steel broadsword",
            "steel katana",
            "steel longsword",
            "steel saber",
        },
        long_blade_two_hand = {
            "dwarven claymore",
            "iron claymore",
            "nordic claymore",
            "silver claymore",
            "steel claymore",
            "steel dai-katana",
        },
        blunt_one_hand = {
            "chitin club",
            "dreugh club",
            "dwarven mace",
            "iron club",
            "iron mace",
            "spiked club",
            "steel club",
            "steel mace",
        },
        blunt_two_hand_close = {
            "dwarven warhammer",
            "iron warhammer",
            "steel warhammer",
        },
        blunt_two_hand_wide = {
            "dreugh staff",
            "silver staff",
            "steel staff",
            "wooden staff",
        },
        spear = {
            "chitin spear",
            "dwarven halberd",
            "dwarven spear",
            "iron halberd",
            "iron long spear",
            "iron spear",
            "silver spear",
            "steel halberd",
            "steel spear",
        },
        axe_one_hand = {
            "chitin war axe",
            "dwarven war axe",
            "iron war axe",
            "silver war axe",
            "steel axe",
            "steel war axe",
        },
        axe_two_hand = {
            "dwarven battle axe",
            "iron battle axe",
            "nordic battle axe",
            "orcish battle axe",
            "steel battle axe",
        },
        bow = {
            "bonemold long bow",
            "chitin short bow",
            "long bow",
            "short bow",
            "steel longbow",
        },
        crossbow = {
            "dwarven crossbow",
            "steel crossbow",
        },
        thrown = {
            "chitin throwing star",
            "iron throwing knife",
            "silver dart",
            "silver throwing star",
            "steel dart",
        },
        arrow = {
            "bonemold arrow",
            "chitin arrow",
            "iron arrow",
            "silver arrow",
            "steel arrow",
        },
        bolt = {
            "bonemold bolt",
            "corkbulb bolt",
            "iron bolt",
            "orcish bolt",
            "silver bolt",
            "steel bolt",
        },
    },
    clothing = {
        pants = {
            "common_pants_01",
            "common_pants_01_a",
            "common_pants_01_e",
            "common_pants_01_u",
            "common_pants_01_z",
            "common_pants_02",
            "common_pants_03",
            "common_pants_03_b",
            "common_pants_03_c",
            "common_pants_04",
            "common_pants_04_b",
            "common_pants_05",
            "expensive_pants_01",
            "expensive_pants_01_a",
            "expensive_pants_01_e",
            "expensive_pants_01_u",
            "expensive_pants_01_z",
            "expensive_pants_02",
            "expensive_pants_03",
            "exquisite_pants_01",
            "extravagant_pants_01",
            "extravagant_pants_02",
        },
        shoes = {
            "common_shoes_01",
            "common_shoes_02",
            "common_shoes_03",
            "common_shoes_04",
            "common_shoes_05",
            "expensive_shoes_01",
            "expensive_shoes_02",
            "expensive_shoes_03",
            "exquisite_shoes_01",
            "extravagant_shoes_01",
            "extravagant_shoes_02",
        },
        shirt = {
            "common_shirt_01",
            "common_shirt_01_a",
            "common_shirt_01_e",
            "common_shirt_01_u",
            "common_shirt_01_z",
            "common_shirt_02",
            "common_shirt_02_h",
            "common_shirt_02_r",
            "common_shirt_02_t",
            "common_shirt_03",
            "common_shirt_03_b",
            "common_shirt_03_c",
            "common_shirt_04",
            "common_shirt_04_a",
            "common_shirt_04_b",
            "common_shirt_04_c",
            "common_shirt_05",
            "expensive_shirt_01",
            "expensive_shirt_01_a",
            "expensive_shirt_01_e",
            "expensive_shirt_01_u",
            "expensive_shirt_01_z",
            "expensive_shirt_02",
            "expensive_shirt_03",
            "exquisite_shirt_01",
            "extravagant_shirt_01",
            "extravagant_shirt_01_h",
            "extravagant_shirt_01_r",
            "extravagant_shirt_01_t",
            "extravagant_shirt_02",
        },
        belt = {
            "common_belt_01",
            "common_belt_02",
            "common_belt_03",
            "common_belt_04",
            "common_belt_05",
            "expensive_belt_01",
            "expensive_belt_02",
            "expensive_belt_03",
            "exquisite_belt_01",
            "extravagant_belt_01",
            "extravagant_belt_02",
        },
        robe = {
            "common_robe_01",
            "common_robe_02",
            "common_robe_02_h",
            "common_robe_02_r",
            "common_robe_02_t",
            "common_robe_03",
            "common_robe_03_a",
            "common_robe_03_b",
            "common_robe_04",
            "common_robe_05",
            "common_robe_05_a",
            "common_robe_05_b",
            "common_robe_05_c",
            "expensive_robe_01",
            "expensive_robe_02",
            "expensive_robe_02_a",
            "expensive_robe_03",
            "exquisite_robe_01",
            "extravagant_robe_01",
            "extravagant_robe_01_a",
            "extravagant_robe_01_b",
            "extravagant_robe_01_c",
            "extravagant_robe_01_h",
            "extravagant_robe_01_r",
            "extravagant_robe_01_t",
            "extravagant_robe_02",
        },
        right_glove = {
            "common_glove_right_01",
            "expensive_glove_right_01",
            "extravagant_glove_right_01",
        },
        left_glove = {
            "common_glove_left_01",
            "expensive_glove_left_01",
            "extravagant_glove_left_01",
        },
        skirt = {
            "common_skirt_01",
            "common_skirt_02",
            "common_skirt_03",
            "common_skirt_04",
            "common_skirt_04_c",
            "common_skirt_05",
            "expensive_skirt_01",
            "expensive_skirt_02",
            "expensive_skirt_03",
            "exquisite_skirt_01",
            "extravagant_skirt_01",
            "extravagant_skirt_02",
        },
        ring = {
            "common_ring_01",
            "common_ring_02",
            "common_ring_03",
            "common_ring_04",
            "common_ring_05",
            "expensive_ring_01",
            "expensive_ring_02",
            "expensive_ring_03",
            "exquisite_ring_01",
            "exquisite_ring_02",
            "extravagant_ring_01",
            "extravagant_ring_02",
        },
        amulet = {
            "common_amulet_01",
            "common_amulet_02",
            "common_amulet_03",
            "common_amulet_04",
            "common_amulet_05",
            "expensive_amulet_01",
            "expensive_amulet_02",
            "expensive_amulet_03",
            "exquisite_amulet_01",
            "extravagant_amulet_01",
            "extravagant_amulet_02",
        },
    },
}
